stages:
  - build --stacktrace

build:
  stage: build --stacktrace
  script:
    - gradle build
  only:
    - CSSE375          # Only build the master git branch
  tags:
    - gradle      # Matches the tags you created for your runner