stages:
  - build

build:
  stage: build
  script:
    - gradle build --info
  only:
    - CSSE375          # Only build the master git branch
  tags:
    - gradle      # Matches the tags you created for your runner